#!/usr/bin/env python
import sys
import socket
import time
import subprocess
import ConfigParser
import logging
from optparse import OptionParser

import yaml

from munin import MuninClient

DEFAULT_CONFIG = {
		'config_file': '/etc/mfg.ini',
		'carbon_port': 2003,
		'metric_prefix': '{hostname}.',
		'interval': 60
		}

def facter():
    try:
        p = subprocess.Popen(['facter','-py'], stdout=subprocess.PIPE)
        p.wait()
        y = yaml.load(p.stdout)
        logging.debug('Got facts: %s', y)
        return y
    except OSError, e:
        logging.warning('Could not get facts: %s', e)
        return None

def compute_prefix(facts, prefix_pattern):
    """
    >>> prefix = 'servers.{datacenter}.{hostname}.'
    >>> facts = {'datacenter':'eu-west', 'hostname':'kellerautomat'}
    >>> compute_prefix(facts, prefix)
    'servers.eu-west.kellerautomat.'
    >>> prefix = '{hostname}.'
    >>> facts = None
    >>> compute_prefix(facts, prefix) == socket.gethostname() + '.'
    True
    """
    try:
        if facts:
            return prefix_pattern.format(**facts)
        else:
            return prefix_pattern.format(hostname=socket.gethostname())
    except KeyError, e:
        logging.error('not all facts in "%s" could be resolved: %s', prefix_pattern, e)
        raise

class CarbonClient(object):

    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self._init_socket()

    def _init_socket(self):
        self.sock = socket.socket()
        self.sock.connect((self.host, self.port))

    def send(self, message):
        self.sock.sendall(message)


def parse_config_file(config_file):
    config_file_structure = (
		    ('carbon_port', 'carbon', 'port'),
		    ('carbon_host', 'carbon', 'host'),
		    ('metric_prefix', 'facter', 'prefix'),
		    ('interval', 'mfg', 'interval'),
		    )
    
    c = ConfigParser.ConfigParser()
    c.read(config_file)
    host = c.get('carbon','host')
    for config_key, section, key in config_file_structure:
	    try:
		port = c.get('carbon','port')
	    except ConfigParser.Error:
		logging.warning('Could not get carbon port from config %s, using %s', config_file, DEFAULT_CARBON_PORT)
		port = DEFAULT_CARBON_PORT

    try:
        prefix_pattern = c.get('facter', 'prefix')
    except ConfigParser.Error:
        logging.warning('Could not get facter prefix from config %s, using %s', config_file, DEFAULT_FACTER_PREFIX)
        prefix_pattern = DEFAULT_FACTER_PREFIX

    try:
        interval = c.getint('mfg', 'interval')
    except ConfigParser.Error:
        interval = 60

    return host, port, prefix_pattern, interval

def parse_command_line():
    # TODO
    parser = OptionParser()
    parser.add_option("-c", "--config", dest="config_file",
            help="use configuration in FILE, default: %s" % DEFAULT_CONFIG['config_file'], metavar="FILE")
    parser.add_option("-i", "--interval", dest="interval",
            help="send metrics every SECONDS, default: %s" % DEFAULT_CONFIG['interval'], metavar="SECONDS")
    parser.add_option("-H", "--carbon-host",
            help="send metrics to carbon host HOST", metavar="HOST")
    parser.add_option("-p", "--carbon-port",
            help="use carbon port PORT, default: %s" % DEFAULT_CONFIG['carbon_port'], metavar="PORT")
    parser.add_option("-m", "--metric-prefix", dest="prefix",
            help="prefix every sent metric with PREFIX, default: %s" % DEFAULT_CONFIG['metric_prefix'], metavar="PREFIX")
    parser.add_option("-v", "--verbose", action="count", dest="verbose", help="be more verbose")

    (options, args) = parser.parse_args()
    logging.getLogger().setLevel((logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG)[max(options.verbose, 3)])
    logging.debug('command line options: %s', options)
    return options.__dict__

def fetch_from_munin(munin_client):
    logging.debug('going to ask munin for items')
    list_result = munin_client.list()
    logging.debug('munin: list command returned %d results', len(list_result))
    timestamp = int(time.time())
    messages = []
    for item in list_result:
        values = munin_client.fetch(item)
        for key in values:
            message = "%s.%s %s %d\n" % (item, key, values[key], timestamp)
            logging.debug('fetched from munin: %s', message)
            messages.append(message)

    return messages

def send_to_carbon(carbon_client, prefix, messages):
    prefixed_messages = [prefix + message for message in messages]
    carbon_client.send("".join(messages))
    logging.info('sent %d messages', len(messages))

def main():
    config_file = DEFAULT_CONFIG['config_file']
    command_line_config = parse_command_line()
    if 'config_file' in command_line_config:
        config_file = command_line_config['config_file']


    config_from_file = parse_config_file(config_file)

    config = default_config.copy()
    config.update(config_from_file)
    config.update(command_line_config)
    
    facts = facter()

    prefix = compute_prefix(facts, config['prefix_pattern'])
    carbon_client = CarbonClient(config['host'], config['port'])
    munin_client = MuninClient('127.0.0.1')

    while True:
        started = time.time()
        next_iteration = started + config['interval']

        messages = fetch_from_munin(munin_client)
        send_to_carbon(carbon_client, prefix, messages)

        now = time.time()
        remaining_sleep = next_iteration - now
        if remaining_sleep > 0:
            logging.debug('sleeping %d', remaining_sleep)
            time.sleep(remaining_sleep)
        else:
            logging.warning('processing took %d seconds more than interval(%d), increase interval', -remaining_sleep, interval)

if __name__ == '__main__':
    logging.root.name = 'mfg'
    logging.basicConfig(level=logging.DEBUG)
    main()
